### ISSUE TITLE
Demo currently broken

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1450]
When trying to run the demo on the current branch, the following error appears:

![image](https://github.com/swisspost/design-system/assets/1659006/aaec7cb8-7872-456f-b6c1-f1320b865131)

```
core.mjs:8400 ERROR TypeError: this._elementRef.nativeElement.closest is not a function
    at new NgbDropdown (ng-bootstrap.mjs:6433:55)
    at NodeInjectorFactory.NgbDropdown_Factory [as factory] (ng-bootstrap.mjs:6733:17)
    at getNodeInjectable (core.mjs:3431:44)
    at instantiateAllDirectives (core.mjs:10997:27)
    at createDirectivesInstances (core.mjs:10470:5)
    at Module.ɵɵtemplate (core.mjs:13465:9)
    at AppComponent_Template (app.component.html:2:3)
    at executeTemplate (core.mjs:10441:9)
    at renderView (core.mjs:10263:13)
    at renderComponent (core.mjs:11434:5)
```

It's possibly broken after minor/patch updates, but needs further investigation.

**Comment by oliverschuerch** [comment]
I have downgraded the ng-bootstrap version from 14.2.0 to 14.1.1 and the error is gone.
Need to dive deeper, to check if there is something in our code, that can not be used anymore in the new Version.

**Comment by oliverschuerch** [comment]
I probably found the issuer:
Source: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md
![Image](https://github.com/swisspost/design-system/assets/9716662/a085947e-8a4c-470a-ad3a-acd0e36546f3)
